version: '3.8'

services:
  app:
    build:
      context: .
    image: user-domain:v1.0
    container_name: userDomain
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network: